server:
  servlet:
    context-path: /api
  port: 8080 #默认端口8080
spring:
  session: #session超时时间 一天
    timeout: 86400 #s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center #jdbc:mysql://localhost:3306/+自己的数据库架构名称
    username: root #统一
    password: 252748377 #自己数据库密码

